spring
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      fail-fast: true
      discovery.enabled: true
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: localhost
